### PR TITLE
Check for working with current EXEC

### PR DESCRIPTION
**Pull request by catherdersoftware**
-----------------------------------
Check the name of the EXEC used to invoke ZIGI. If you're trying to update the repository that uses this EXEC, we stop immediately and tell you thi is a bad idea. You really should use a "prod" ZIGI to work on a dev ZIGI

### CODE REVIEW

**Comment by lbdyck** [comment]
I'm not a big fan of this change - the basic part for the `zigi.exec` is ok but is so limited that it would only apply to a few developers and thus not sure it is warranted while the other changes don't fit (imho).

**Comment by wizardofzos** [comment]
Heya,

What other changes you refer to Lionel?

I do feel this is a bit little for a version bump..... but imho it could go in with other updates?

**Comment by lbdyck** [comment]
look at the commit and you'll see other changes - perhaps just spacing but also a Do/End that wasn't needed.  Definitely *not* a version bump.

**Comment by catherdersoftware** [comment]
> I'm not a big fan of this change - the basic part for the `zigi.exec` is ok but is so limited that it would only apply to a few developers and thus not sure it is warranted while the other changes don't fit (imho).

True, this would only affect people updating zigi, but any extra checking to make sure you don't lose work is always appreciated.

**Pull request merged**
